# Generated by Django 3.1.4 on 2020-12-08 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='month',
            field=models.CharField(default='December', max_length=25),
        ),
        migrations.AddField(
            model_name='timecard',
            name='year',
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(choices=[('ST1', 'Sprint Team 1'), ('ST2', 'Sprint Team 2'), ('ST3', 'Sprint Team 3')], default='SE', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='function',
            field=models.CharField(choices=[('DE', 'Data Engineering'), ('SE', 'Software Engineering'), ('TE', 'Testing'), ('DO', 'DevOps')], default='DE', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='functional_leader',
            field=models.CharField(choices=[('RK', 'Ramesh Kumar'), ('NI', 'Naveen Iyer'), ('SN', 'Suresh Nair'), ('NV', 'Nitin Varma')], default='RK', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='project1',
            field=models.CharField(choices=[('C', 'Corporate'), ('LS', 'Lending Stream'), ('D', 'Drafty')], default='C', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='project2',
            field=models.CharField(choices=[('C', 'Corporate'), ('LS', 'Lending Stream'), ('D', 'Drafty')], default='LS', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='time_project1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='time_project2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='total_time',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_month='date_created'),
        ),
    ]
