# Generated by Django 3.1.4 on 2020-12-08 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20201208_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='month',
            field=models.PositiveIntegerField(default='12'),
        ),
        migrations.AlterField(
            model_name='timecard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.employee', unique_for_month='date_created'),
        ),
    ]
