# Generated by Django 3.1.4 on 2020-12-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20201208_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='month',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
