# Generated by Django 3.1.4 on 2020-12-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0007_auto_20201209_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(choices=[('C', 'Corporate'), ('LS', 'Lending Stream'), ('D', 'Drafty')], default='LS', max_length=25)),
                ('time_project', models.PositiveIntegerField()),
                ('timecard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timecard', to='timesheet.timecard')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
