# Generated by Django 3.1.4 on 2020-12-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timecard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='timesheet.timecard'),
        ),
    ]
