# Generated by Django 3.1.4 on 2020-12-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_auto_20201211_1717'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
