# Generated by Django 3.1.4 on 2020-12-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0010_auto_20201211_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecard',
            name='project2',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='time_project2',
        ),
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.CharField(default='Drafty', max_length=25),
        ),
    ]
